name: Feature
description: Plan a new feature with subtasks
title: "feat: <concise feature name>"
labels: ["type:feature"]
assignees: []
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: What problem are we solving? Link to any Notion doc/spec.
      placeholder: >
        Context, goals, and links to specs or designs.
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: Concrete goals; what behavior or results do we expect when this is done?
      placeholder: |
        - [ ] Goal 1
        - [ ] Goal 2
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: true
  - type: textarea
    id: subtasks
    attributes:
      label: Subtasks (create child issues first, then link them)
      description: Use - [ ] #issue style to link child issues.
      placeholder: |
        - [ ] #<issue-id> Subtask 1
        - [ ] #<issue-id> Subtask 2