name: Feature
description: Plan a new feature with subtasks
title: "feat: <concise feature name>"
labels: ["type:feature"]
assignees: []
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: What problem are we solving? Why now? Link to any Notion doc/spec.
      placeholder: >
        Context, goals, and links to specs or designs.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Concrete "done means" bullets.
      placeholder: |
        - [ ] AC1
        - [ ] AC2
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / Risks
      placeholder: |
        - Blocks/blocked by issues (#123), external services, timing, etc.
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: true
  - type: textarea
    id: subtasks
    attributes:
      label: Subtasks (create child issues first, then link them)
      description: Use - [ ] #issue style to link child issues.
      placeholder: |
        - [ ] #<issue-id> Subtask 1
        - [ ] #<issue-id> Subtask 2
  - type: checkboxes
    id: project_placement
    attributes:
      label: Project placement
      description: New items start in the Backlog view by default. You can move to Todo when ready.
      options:
        - label: I understand new issues will appear in Backlog (default).
          required: true
