name: Fix / Task
description: A concrete, actionable unit of work
title: "fix: <concise fix/task name>"
labels: ["type:fix"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: One or two sentences on what to change or implement.
    validations:
      required: true
  - type: input
    id: parent
    attributes:
      label: Linked Feature (optional)
      description: If this is a subtask, paste the parent Feature issue number like "#123".
      placeholder: "#<feature-issue-id>"
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [P0, P1, P2, P3]
